Fix importlib import (#224)
There was a bug that this package depended on importlib-metadata instead
of the Python3.8 importlib module. When importlib-metadata was not
installed the following error would show:
AttributeError: module 'importlib' has no attribute 'metadata'
https://docs.python.org/3/library/importlib.metadata.html

Followup of https://github.com/google/sedpack/pull/217